// spotipie/src/primary/pages/home/song-card/SongCard.tsx
import React from 'react';
import './SongCard.scss';
import { Artist } from '../../../../domain/Artist';

interface SongCardProps {
  artists: Artist[],
  title: string,
  albumName: string,
	urlImage: string,
}

export function SongCard({ artists, title, albumName, urlImage }: SongCardProps) {
	return (
		<div className="song-card">
			<img className="song-card--img" src={urlImage} alt="song-card-image"/>
			<div className="song-card--text">
				<span>Title: {title}</span>
				<span>Artist: {artists[0].getName()}</span>
				<span>Album: {albumName}</span>
			</div>
		</div>);
}

// spotipie-front/src/components/card/SongCard.vue
<script setup lang="ts">
import TextLabel from '@/components/card/TextLabel.vue'
const ARTISTS_NAME_DELIMITER = ', '
const props = defineProps({
  artists: {
    type: Array<{name: string}>,
    default: []
  },
  title: String,
  albumName: String,
  urlImage: String
})
</script>

<template>
  <div class="card">
    <img class="card--img" :src="urlImage" alt="song-card" />
    <div class="card--text-wrapper">
      <TextLabel label="Artiste(s)" :text="props.artists.map(artist => artist.name).join(ARTISTS_NAME_DELIMITER)" />
      <TextLabel label="Titre" :text="props.title" />
      <TextLabel label="Album" :text="props.albumName" />
    </div>
  </div>
</template>
<style scoped lang="scss">
.card {
  display: flex;

  &--img {
    width: 6rem;
  }

  &--text-wrapper {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    padding: 0.5rem 1rem;
  }
}
</style>
